feat: app test
profianinc/drawbridge pull request #141
Opened 2022-05-19 16:01 UTC by rjzak

Working on signed tag and directory creation.

Signed-off-by: Richard Zak <richard@profian.com>

2022-05-19 16:02 UTC, rjzak commented on crates/app/tests/mod.rs
> +            signature: Signature {
These fields in the Signed tag are causing stack overflow errors. Am I missing something obvious?

2022-05-20 12:10 UTC, rvolosatovs requested changes

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +    let random_bytes = [
This is unmaintainable, what is this variable for? Where did these values come from?
Apart from that `u8` is redundant

If you need random bytes, generate them at runtime.
If you need a constant, use a human-readable string `const`.

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +        Jws::TYPE,
This means you're creating a signed tag of a signed tag

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +            payload: Some(Bytes::from(random_bytes_sha256)),
Why not just store a constant `"test"`? What's the benefit of using a hash here?

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +    println!("Created tag2");
This is too verbose to be printed on each test execution, as a rule of thumb, you should only see output if something is broken

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +    let two_tags = tag::list(&cl, &addr, &foo).await;
```suggestion
    let tags = tag::list(&cl, &addr, &foo).await;
```

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +    println!("Get two tags assertions passed.");
see above, there's no value for this statement, if the assertion wouldn't have passed - you'd see a failure

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +        b"/sub_directory".to_vec(),
This should be a JSON-encoded object mapping names to entries.

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +        &"/sub_directory/testing_file.bin".parse().unwrap(),
this is very verbose, while the verbosity does not bring any value
```suggestion
        &"/foo/bar".parse().unwrap(),
```

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +        random_bytes.to_vec(),
Why not `b"test".to_vec()`?

2022-05-20 12:10 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +        &"/sub_directory/testing_file.bin".parse().unwrap(),
see above

2022-05-20 12:10 UTC, rvolosatovs commented on crates/jose/src/jws.rs
> +    pub const TYPE: &'static str = "application/jose+json";
Redundant, see https://github.com/profianinc/drawbridge/pull/141/files#diff-f489372ea9f1f61671d0178d79df7eb4bd7d9ebcf7b0d7e8308592705e2c5732R45 right above

2022-05-20 12:20 UTC, rvolosatovs commented
Please work on your commit messages.
See https://cbea.ms/git-commit/ and then https://www.conventionalcommits.org/en/v1.0.0/

2022-05-20 12:22 UTC, rvolosatovs commented on crates/app/tests/mod.rs
> +            signature: Signature {
The `random_bytes_sha256` is not a valid `JWS` (you're trying to store a signed tag in a signed tag)

2022-05-20 13:56 UTC, rjzak commented on crates/app/tests/mod.rs
> +            signature: Signature {
How do I use JWS properly? Removing anything and the compiler complains about incorrect datatype.

2022-05-24 13:43 UTC, closed without merging