docs: add server example
profianinc/drawbridge pull request #153
Opened 2022-06-10 13:45 UTC by bstrie

This doubles as a convenient way to run a local server for testing.

Signed-off-by: bstrie <865233+bstrie@users.noreply.github.com>

2022-06-10 14:03 UTC, rjzak commented
How is this different from `src/main.rs`?

2022-06-10 14:17 UTC, rvolosatovs requested changes
Same question as https://github.com/profianinc/drawbridge/pull/153#issuecomment-1152397268

I'm not sure what the value of this is and whether or not it outweighs the maintenance cost.

I see two reasons why this could be useful:
1. Running a local Drawbridge instance for testing.
- If this is what we want it for, then it should run on the same port as "usual" `src/main.rs`
- I am not convinced that this is better than `cargo run -- $(mktemp -d)` or running the binary directly
- How do you stop this? We probably want signal handling here, wouldn't `cargo` capture these?
2. Providing an example of running a custom Drawbridge instance.
- We should definitely not suggest people to run this in a world-readable temporary directory
- What certificates are we going to use in this example once we have support for that?
- At least for now `src/main.rs` does not have anything "custom" there that would prevent for it to be used as a "template"

If we need this for 1. - let's make this as similar to `src/main.rs` as possible reusing as much code as possible, although I think using the actual binary is way more useful for testing purposes.
If we need this for 2. - let's encourage secure practices - maybe create a `700` directory and use that at least? We also need to document all the steps here then

2022-06-10 14:23 UTC, bstrie commented
> If this is what we want it for, then it should run on the same port as "usual" src/main.rs

Isn't 0.0.0.0 reachable from the outside? This is just for testing, I only want it exposed to localhost.

> I am not convinced that this is better than cargo run -- $(mktemp -d) or running the binary directly

I was just annoyed at making a temp directory manually. :P

> How do you stop this? We probably want signal handling here, wouldn't cargo capture these?

Just Ctrl+C, the OS cleans up tmp regularly.

> We should definitely not suggest people to run this in a world-readable temporary directory

What secrets are we storing?

> What certificates are we going to use in this example once we have support for that?

We're still going to need some way to run a local server for testing, so this can work the same way.

2022-06-10 14:30 UTC, rjzak commented
Maybe this is a fine addition for local testing for an individual and maybe not for the project.

2022-06-10 14:34 UTC, rvolosatovs commented
> Isn't 0.0.0.0 reachable from the outside? This is just for testing, I only want it exposed to localhost.

It depends on the system, `0.0.0.0` means to listen on all interfaces


> I was just annoyed at making a temp directory manually. :P

Fair enough, but to make this more useful I think we need a flag here to specify whether the directory should be persisted or not (note the `.path()` and `into_path()` distinction on `tempdir()`)


> Just Ctrl+C, the OS cleans up tmp regularly.

If we want to use this for testing, we should assert clean, graceful shutdown. Just killing the server is not "good enough" for this purpose



> What secrets are we storing?

Drawbridge will store very sensitive data (user's applications and potentially even secrets)


Let's have this for testing, but let's call it `test-server` then and make it a bit more useful for the purpose

2022-06-10 14:36 UTC, rvolosatovs commented on examples/server.rs
> +    let socket = (Ipv4Addr::LOCALHOST, 12345).into();
Either run on the same port as production instance, or run on `:0` and print the value on startup

2022-06-10 14:38 UTC, rvolosatovs commented on examples/server.rs
> +    let store = tempdir().unwrap();
I think we need to add support for persisting this and also take an already-existing directory in.

2022-06-13 12:02 UTC, bstrie commented
Closing this for now to focus on other things.

2022-06-13 12:02 UTC, closed without merging