chore:namespace refactor
profianinc/drawbridge pull request #68
Opened 2022-04-20 19:34 UTC by rjzak

Signed-off-by: Richard Zak <richard@profian.com>

2022-04-21 09:01 UTC, rvolosatovs requested changes
Can we have 2 commits here:
1. Extract `namespace` into a separate module
2. Add routing tests
?

2022-04-21 09:01 UTC, rvolosatovs commented on crates/repo/src/lib.rs
>      fn namespace_from_str() {
This test should be moved to `namespace.rs` and renamed to `from_str`

2022-04-21 09:02 UTC, rvolosatovs commented on crates/repo/src/namespace.rs
> +#![forbid(unsafe_code)]
```suggestion
```

2022-04-21 09:11 UTC, rvolosatovs commented on crates/repo/src/lib.rs
> +                .serve(app().into_make_service())
What if port `8000` is already used?

Let's do exactly what we already do in main with no custom logic
https://github.com/profianinc/drawbridge/blob/19f8f307bcd7b30f921aa3d96a2876bca0cb73c6/src/main.rs#L14

2022-04-21 09:11 UTC, rvolosatovs commented on crates/repo/src/lib.rs
> +        let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
What I would expect to happen here, would be a `GET` on non-existing repo, asserting a 404, then `PUT` to that repo asserting 200, then `GET` on the same repo now succeeding and asserting 200.

2022-04-21 09:14 UTC, rvolosatovs commented
Also:
- please add "Closes #<issue number>" to PR descriptions of PRs closing issues. (just reference issues if they are related, but PR does not close them)
- ensure there's a space between the <type> in the commit message and the description, i.e. `chore: something` and *not* `chore:something`

2022-04-21 15:50 UTC, rjzak commented on crates/repo/src/lib.rs
> +        tokio::spawn(async move {
@rvolosatovs The client fails to connect and I think there is an issue here getting the connection opened.

2022-04-22 15:16 UTC, rvolosatovs requested changes
See https://github.com/profianinc/drawbridge/pull/68#discussion_r854962527

2022-04-22 15:16 UTC, rvolosatovs commented on crates/repo/src/lib.rs
> +    use namespace::Namespace;
unused

2022-04-22 18:16 UTC, rjzak commented
I don't understand what happened, I rebased based on the changed upstream main, and now the upstream commits are now added to this PR?

2022-04-25 09:12 UTC, rvolosatovs commented
> I don't understand what happened, I rebased based on the changed upstream main, and now the upstream commits are now added to this PR?

Let's try to go through the process together after standup

2022-04-26 09:07 UTC, rvolosatovs reviewed
A few improvements/fixes:
- `Content-Type` should not be specified on `GET` (although we should probably add `Accept` here later)
- `GET` is default, so do not specify it
- Added a `request_builder()` helper
- Removed the amount of assignments, so it's a bit clearer what we are asserting
- Imported the header constants
- Added `Content-Length` on `PUT`
- Added a few more test cases, especially error cases

```diff
diff --git a/crates/repo/src/lib.rs b/crates/repo/src/lib.rs
index 371deaa..78df45e 100644
--- a/crates/repo/src/lib.rs
+++ b/crates/repo/src/lib.rs
@@ -234,39 +234,94 @@ pub fn app() -> Router {
 mod tests {
     use super::*;
 
+    use axum::http::header::{CONTENT_LENGTH, CONTENT_TYPE};
+    use axum::http::request;
+
     #[tokio::test]
     async fn routes() {
-        const REPO_URL: &str = "http://127.0.0.1:8080/test/onetwothree";
+        const URL: &str = "http://127.0.0.1:8080/test/onetwothree";
+        fn request_builder() -> request::Builder {
+            Request::builder().uri(URL)
+        }
+
         let mut router = app();
 
-        let error_request = Request::builder()
-            .method("GET")
-            .header(axum::http::header::CONTENT_TYPE, "application/json")
-            .uri(REPO_URL)
-            .body(Body::empty())
+        let res = router
+            .call(request_builder().body(Body::empty()).unwrap())
+            .await
+            .unwrap();
+        assert_eq!(res.status(), StatusCode::NOT_FOUND);
+
+        let res = router
+            .call(
+                request_builder()
+                    .method("PUT")
+                    .header(CONTENT_LENGTH, 3)
+                    .header(CONTENT_TYPE, "application/json")
+                    .body(Body::from("{}"))
+                    .unwrap(),
+            )
+            .await
             .unwrap();
+        assert_eq!(res.status(), StatusCode::BAD_REQUEST);
 
-        let error_response = router.call(error_request).await.unwrap();
-        assert_eq!(error_response.status().as_u16(), 404);
+        let res = router
+            .call(
+                request_builder()
+                    .method("PUT")
+                    .header(CONTENT_LENGTH, 2)
+                    .header(CONTENT_TYPE, "application/toml")
+                    .body(Body::from("{}"))
+                    .unwrap(),
+            )
+            .await
+            .unwrap();
+        assert_eq!(res.status(), StatusCode::UNSUPPORTED_MEDIA_TYPE);
 
-        let put_request = Request::builder()
-            .method("PUT")
-            .header(axum::http::header::CONTENT_TYPE, "application/json")
-            .uri(REPO_URL)
-            .body(Body::from("{}"))
+        let res = router
+            .call(
+                request_builder()
+                    .method("PUT")
+                    .header(CONTENT_LENGTH, 13)
+                    .header(CONTENT_TYPE, "application/json")
+                    .body(Body::from(r#"{"one":"two"}"#))
+                    .unwrap(),
+            )
+            .await
             .unwrap();
+        assert_eq!(res.status(), StatusCode::UNPROCESSABLE_ENTITY);
 
-        let put_response = router.call(put_request).await.unwrap();
-        assert_eq!(put_response.status().as_u16(), 200);
+        let res = router
+            .call(
+                request_builder()
+                    .method("PUT")
+                    .header(CONTENT_LENGTH, 2)
+                    .header(CONTENT_TYPE, "application/json")
+                    .body(Body::from("{}"))
+                    .unwrap(),
+            )
+            .await
+            .unwrap();
+        assert_eq!(res.status(), StatusCode::OK);
 
-        let successful_request = Request::builder()
-            .method("GET")
-            .header(axum::http::header::CONTENT_TYPE, "application/json")
-            .uri(REPO_URL)
-            .body(Body::empty())
+        // TODO: This should not result in conflict, since payload is the same.
+        let res = router
+            .call(
+                request_builder()
+                    .method("PUT")
+                    .header(CONTENT_LENGTH, 2)
+                    .header(CONTENT_TYPE, "application/json")
+                    .body(Body::from("{}"))
+                    .unwrap(),
+            )
+            .await
             .unwrap();
+        assert_eq!(res.status(), StatusCode::CONFLICT);
 
-        let successful_response = router.call(successful_request).await.unwrap();
-        assert_eq!(successful_response.status().as_u16(), 200);
+        let res = router
+            .call(request_builder().body(Body::empty()).unwrap())
+            .await
+            .unwrap();
+        assert_eq!(res.status(), StatusCode::OK);
     }
 }
```

2022-04-26 13:49 UTC, rvolosatovs approved these changes

2022-04-26 14:02 UTC, merged